#!/usr/bin/env python
#
# Copyright 2012 SUSE Linux
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import argparse
import glob
import os
import re
import tarfile


def read_from_tarball(tar_name, filename):

    try:
        tar = tarfile.open(tar_name)

        try:
            changelog_file = min((f for f in tar.getnames()
                                  if f.endswith(filename)),
                                 key=len)
        except ValueError:
            raise Exception("Coud not find a file %s in %s" %
                            (filename, tar_name))
        t = tar.getmember(changelog_file)
        changelog = tar.extractfile(t).read()
    finally:
        tar.close()
    return changelog


def parse_update_spec_file(specfile, contents, run_requires):

    found_requires = set()
    all_requires = set()

    for d in run_requires:

        all_requires.add(d)

        if re.search(r'^(Build)?Requires:\s+%s' % (d), contents,
                     flags=re.MULTILINE | re.IGNORECASE) >= 0:
            found_requires.add(d)

        if run_requires[d]:
            contents = re.sub(
                r'^(Requires:[ \t]+)(%s)(?:[ \t].*)?$' % (d),
                r'\g<1>\g<2> >= %s' % (run_requires[d]),
                contents, flags=re.MULTILINE | re.IGNORECASE)[:]

    if not specfile.endswith("-doc.spec"):
        spec_requires = set()
        for m in re.finditer(r"^Requires:[ \t]+python-([\w\d\.-]+)",
                             contents, flags=re.MULTILINE | re.IGNORECASE):
            spec_requires.add("python-%s" % m.group(1))

        if all_requires.difference(found_requires):
            for d in all_requires.difference(found_requires):
                print("ERROR: %s is missing in %s" % (d, specfile))

        for d in spec_requires.difference(all_requires):
            if d.lower() in all_requires:
                continue
            print("W: %s is not found in upstream" % d)

    return contents


def update_spec_files(run_requires):
    for specfile in glob.glob('./*.spec'):
        try:
            f = open(specfile, 'r+')
            contents = f.read()
            f.seek(0)
            f.truncate()
            contents = parse_update_spec_file(specfile, contents, run_requires)
            f.write(contents)
        finally:
            f.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Python Requires')
    parser.add_argument('--outdir',
                        help='osc service parameter that does nothing')
    args = parser.parse_args()

    # Try to find the tarball
    candidates = set()
    for d in os.listdir('.'):
        if '.tar.' in d:
            candidates.add(d)

    candidates = list(candidates)
    candidates.sort(key=lambda i: (-len(i)))
    filename = candidates[0]

    run_requires = read_from_tarball(filename, '/requirements.txt')

    try:
        test_requires = read_from_tarball(filename, '/test-requirements.txt')
    except Exception:
        test_requires = ""
        pass

    d = dict()

    for l in run_requires.split('\n') + test_requires.split('\n'):
        # strip away comments
        l = re.sub('#.*', ' ', l)
        # strip away whitespace
        l = re.sub('[ \t]*', '', l)

        l = l.partition(',')[0]

        if not l or l.startswith("-f"):
            continue

        m = re.match('^http://tarballs.openstack.org/([^/]+)/', l)
        if m:
            l = m.group(1)

        if re.match('^python-(.*)client', l):
            l = re.sub(r'^python-(.+client)', r'\g<1>', l)

        r = re.match("^(.*)[<>=]=([^ ]*)", l)
        if r:
            d["python-%s" % (r.group(1))] = r.group(2)

        elif len(l):
            d["python-%s" % (l)] = None

    ignore_requires = (
        'python-coverage',
        'python-sphinx', 'python-setuptools_git',
        'python-setuptools',
        'python-setuptools-git', 'python-distribute',
        'python-pylint', 'python-hacking',
        'python-docutils', 'python-oslo.sphinx', 'python-oslosphinx')

    real_requires = dict()
    for k in set(d.keys()).difference(ignore_requires):
        real_requires[k] = d[k]

    update_spec_files(real_requires)
